version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11
      environment: # environment variables for primary container
    working_directory: /go/src/github.com/sydy_ci
    steps:
    - checkout
    - run: echo "checkouut"
        
    - run: echo "test"
    
    - run: echo "A first hello"

    - setup_remote_docker:
        docker_layer_caching: true
    - run:
            name: build and push Docker images
            shell: /bin/bash
            command: |
              chmod +x ../build.sh
              ../build.sh
