version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11
    working_directory: /go/src/syudy_ci
    steps:
    - checkout
    - run: echo "checkouut"
        
    - run: echo "test"
    
    - run: echo "A first hello"

    - setup_remote_docker:
        docker_layer_caching: false
    - run:
            name: build and push Docker images
            shell: /bin/bash
            command: |
              chmod 777 ./../build.sh
              ./../build.sh
