apiVersion: apps/v1
kind: Deployment
metadata:
 name: cricle
 labels:
  name: cricle
spec:
 replicas: 3
 strategy:
  type: RollingUpdate
 selector:
  matchLabels:
   name: cricle
 template:
  metadata:
   labels:
    name: cricle
  spec:
   containers:                  
    - name: cricle
      image: 1142051133/cricile:0.3.45
      ports:
       - containerPort: 9090