apiVersion: v1
kind: Service
metadata:
 name: cricle-service-http
spec:
 selector:
  name: cricle-service
 type: NodePort
 ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30036
    name: cricle-service
